services:
  web:
    image: nginx:alpine
    container_name: darkweb_nginx
    volumes:
      - ./web/:/usr/share/nginx/html/
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    restart: unless-stopped

  tor:
    image: alpine:latest
    container_name: darkweb_tor
    command: sh -c "apk add --no-cache tor && su tor -s /bin/sh -c 'tor -f /etc/tor/torrc'"
    user: "0:0"
    volumes:
      - ./tor/:/etc/tor/
      # Removed hidden_service bind mount to avoid permission issues
    depends_on:
      - web
    restart: unless-stopped


